export const PROFILE = {
  name: 'Vishesh Mahendru',
  role: 'Brand & Visual Designer',
  experience: '3–4 years',
  skills: 'Brand identity, packaging, web design, Blender 3D, Figma, Framer',
  portfolio: 'visheshmahendru.com',
  email: 'visheshmahendru11@gmail.com',
  phone: '+91 74885 85613',
}

export const JOBS = [
  {
    id: 1,
    title: 'Senior Brand Designer',
    company: 'Studio Retype',
    location: 'Remote',
    type: 'Full-time',
    salary: '$80–100k',
    email: 'careers@studioretype.com',
    tags: ['Identity', 'Typography'],
    posted: '2h',
    match: 97,
    why: 'Identity systems + type-led work maps directly to your portfolio and MESA direction.',
  },
  {
    id: 2,
    title: 'Visual Designer',
    company: 'Someplace Studio',
    location: 'Remote · EU',
    type: 'Full-time',
    salary: '€60–75k',
    email: 'hello@someplace.studio',
    tags: ['Brand', 'Motion'],
    posted: '5h',
    match: 94,
    why: 'Studio does brand + web end-to-end — matches your full-stack design range.',
  },
  {
    id: 3,
    title: 'Brand Identity Designer',
    company: 'KOTO Studio',
    location: 'Remote',
    type: 'Contract',
    salary: '$70–90k',
    email: 'apply@koto.studio',
    tags: ['Identity', 'Systems'],
    posted: '1d',
    match: 91,
    why: 'Systems-driven identity work; your structured token approach is a direct fit.',
  },
  {
    id: 4,
    title: 'Design Lead',
    company: 'Monograph',
    location: 'Remote · Global',
    type: 'Full-time',
    salary: '$90–120k',
    email: 'design@monograph.io',
    tags: ['Leadership', 'Product'],
    posted: '1d',
    match: 88,
    why: 'Product + brand hybrid; your app-building work covers the product half.',
  },
  {
    id: 5,
    title: 'Graphic Designer',
    company: 'Hawkins\\Brown',
    location: 'Remote · UK',
    type: 'Full-time',
    salary: '£45–55k',
    email: 'studio@hawkinsbrown.com',
    tags: ['Brand', 'Print'],
    posted: '2d',
    match: 85,
    why: 'Architecture studio needing editorial brand work — your cinematic register fits.',
  },
  {
    id: 6,
    title: 'Creative Director',
    company: 'Athletics',
    location: 'Remote',
    type: 'Full-time',
    salary: '$110–140k',
    email: 'join@athletics.com',
    tags: ['Direction', 'Strategy'],
    posted: '2d',
    match: 82,
    why: 'Stretch role — strategy emphasis exceeds your current years, but portfolio depth compensates.',
  },
  {
    id: 7,
    title: 'Brand Designer',
    company: 'Superside',
    location: 'Remote · Global',
    type: 'Full-time',
    salary: '$65–85k',
    email: 'talent@superside.com',
    tags: ['Brand', 'Scale'],
    posted: '3d',
    match: 80,
    why: 'High-volume brand production; pays less per project but steady remote income.',
  },
  {
    id: 8,
    title: 'Visual Identity Designer',
    company: 'DesignStudio',
    location: 'Remote · EU/US',
    type: 'Full-time',
    salary: '$75–95k',
    email: 'work@design.studio',
    tags: ['Identity', 'Research'],
    posted: '3d',
    match: 78,
    why: 'Research-heavy process; your audit-tool thinking translates, but slower pace.',
  },
]

const ago = (n) => { const d = new Date(); d.setDate(d.getDate() - n); return d.toISOString() }

export const INITIAL_PIPELINE = [
  { id: 101, title: 'Brand Designer',        company: 'Figma',  email: 'design-jobs@figma.com',  stage: 'sent',      sentAt: ago(8),  followUps: 0 },
  { id: 102, title: 'Visual Designer',        company: 'Linear', email: 'careers@linear.app',     stage: 'opened',    sentAt: ago(3),  followUps: 0 },
  { id: 103, title: 'Sr. Brand Designer',     company: 'Loom',   email: 'hiring@loom.com',        stage: 'replied',   sentAt: ago(5),  followUps: 1 },
  { id: 104, title: 'Brand Designer',         company: 'Vercel', email: 'design@vercel.com',      stage: 'interview', sentAt: ago(12), followUps: 1 },
]

export const STAGES = [
  { id: 'sent',      label: 'Sent',      color: '#52504c' },
  { id: 'opened',    label: 'Opened',    color: '#f2994a' },
  { id: 'replied',   label: 'Replied',   color: '#b8f5a0' },
  { id: 'interview', label: 'Interview', color: '#6fcf97' },
]
