// Jobs start visible — user dismisses what they don't want, applies to what they do.
// Pipeline starts EMPTY — nothing fake pre-populated.
// Gmail connection is NOT pre-assumed.

export const DEFAULT_PROFILE = {
  name: '',
  role: '',
  experience: '',
  skills: '',
  about: '',
  portfolio: '',
  email: '',
  phone: '',
  resumeName: null,
  portfolioFileName: null,
}

// Mock jobs use real apply URLs only. No invented email addresses.
// Email field is null unless a studio publicly lists one on their site.
export const JOBS = [
  {
    id: 1,
    title: 'Brand Designer',
    company: 'Superside',
    location: 'Remote, Global',
    workType: 'Remote',
    type: 'Full-time',
    salary: '$65–85k',
    salaryNum: 75,
    email: null,
    applyUrl: 'https://superside.com/careers',
    tags: ['Brand', 'Scale', 'Systems'],
    posted: '2d',
    match: 88,
    why: 'High-volume remote brand work. Consistent output across identity and digital is the core requirement.',
  },
  {
    id: 2,
    title: 'Senior Visual Designer',
    company: 'Framer',
    location: 'Remote',
    workType: 'Remote',
    type: 'Full-time',
    salary: '$80–110k',
    salaryNum: 95,
    email: null,
    applyUrl: 'https://www.framer.com/jobs/',
    tags: ['Visual', 'Product', 'Web'],
    posted: '3d',
    match: 85,
    why: 'You already build in Framer. This is a direct skills match, plus portfolio evidence.',
  },
  {
    id: 3,
    title: 'Brand Designer',
    company: 'Linear',
    location: 'Remote',
    workType: 'Remote',
    type: 'Full-time',
    salary: '$90–120k',
    salaryNum: 105,
    email: null,
    applyUrl: 'https://linear.app/careers',
    tags: ['Brand', 'Identity', 'Systems'],
    posted: '4d',
    match: 82,
    why: 'Linear does systematic, high-craft brand work. Your token-based approach is the right fit.',
  },
  {
    id: 4,
    title: 'Design Lead',
    company: 'Loom',
    location: 'Remote',
    workType: 'Remote',
    type: 'Full-time',
    salary: '$100–130k',
    salaryNum: 115,
    email: null,
    applyUrl: 'https://www.loom.com/careers',
    tags: ['Leadership', 'Brand', 'Product'],
    posted: '5d',
    match: 79,
    why: 'Hybrid brand and product scope. App-building background covers the product side.',
  },
  {
    id: 5,
    title: 'Visual Designer',
    company: 'Vercel',
    location: 'Remote',
    workType: 'Remote',
    type: 'Full-time',
    salary: '$90–120k',
    salaryNum: 105,
    email: null,
    applyUrl: 'https://vercel.com/careers',
    tags: ['Visual', 'Brand', 'Web'],
    posted: '6d',
    match: 83,
    why: 'Dark, typographic, systems-led visual direction. Your aesthetic register is on-brand here.',
  },
  {
    id: 6,
    title: 'Brand Designer',
    company: 'Pitch',
    location: 'Remote',
    workType: 'Remote',
    type: 'Full-time',
    salary: '$70–95k',
    salaryNum: 82,
    email: null,
    applyUrl: 'https://pitch.com/jobs',
    tags: ['Brand', 'Identity', 'Motion'],
    posted: '1w',
    match: 80,
    why: 'Pitch cares about craft and systems. Portfolio needs to show both.',
  },
]

// Second batch — shown after "load more" is clicked
export const JOBS_EXTENDED = [
  {
    id: 9,
    title: 'Brand Designer',
    company: 'Figma',
    location: 'Remote, US',
    workType: 'Remote',
    type: 'Full-time',
    salary: '$100–140k',
    salaryNum: 120,
    email: null,
    applyUrl: 'https://www.figma.com/careers/',
    tags: ['Brand', 'Systems', 'Digital'],
    posted: '4d',
    match: 76,
    why: 'Figma brand team works at the intersection of tool and identity. Strong systems portfolio required.',
  },
  {
    id: 10,
    title: 'Visual Designer',
    company: 'Notion',
    location: 'Remote, US',
    workType: 'Remote',
    type: 'Full-time',
    salary: '$95–130k',
    salaryNum: 112,
    email: null,
    applyUrl: 'https://www.notion.so/careers',
    tags: ['Visual', 'Brand', 'Web'],
    posted: '5d',
    match: 74,
    why: 'Notion brand is minimalist and editorial. Aesthetic register is a close match.',
  },
  {
    id: 11,
    title: 'Digital Designer',
    company: 'Instrument',
    location: 'Portland, US',
    workType: 'Hybrid',
    type: 'Full-time',
    salary: '$70–90k',
    salaryNum: 80,
    email: null,
    applyUrl: 'https://www.instrument.com/careers',
    tags: ['Web', 'Motion', 'Brand'],
    posted: '5d',
    match: 72,
    why: 'Web and motion focused. Framer skills apply directly here.',
  },
  {
    id: 12,
    title: 'Brand Designer',
    company: 'Webflow',
    location: 'Remote',
    workType: 'Remote',
    type: 'Full-time',
    salary: '$85–115k',
    salaryNum: 100,
    email: null,
    applyUrl: 'https://webflow.com/careers',
    tags: ['Brand', 'Web', 'Systems'],
    posted: '6d',
    match: 78,
    why: 'Webflow brand team does system-level design work. Web and identity experience both count.',
  },
]

export const STAGES = [
  { id: 'drafted',   label: 'Drafted',   color: '#4a4a52' },
  { id: 'sent',      label: 'Sent',      color: '#52504c' },
  { id: 'opened',    label: 'Opened',    color: '#f2994a' },
  { id: 'replied',   label: 'Replied',   color: '#b8f5a0' },
  { id: 'interview', label: 'Interview', color: '#6fcf97' },
]
