// Jobs start visible — user dismisses what they don't want, applies to what they do.
// Pipeline starts EMPTY — nothing fake pre-populated.
// Gmail connection is NOT pre-assumed.

export const DEFAULT_PROFILE = {
  name: '',
  role: '',
  experience: '',
  skills: '',
  portfolio: '',
  email: '',
  phone: '',
  resumeName: null,
  portfolioFileName: null,
  photoName: null,
}

export const JOBS = [
  {
    id: 1,
    title: 'Senior Brand Designer',
    company: 'Studio Retype',
    location: 'Remote',
    workType: 'Remote',
    type: 'Full-time',
    salary: '$80–100k',
    salaryNum: 90,
    email: 'careers@studioretype.com',
    tags: ['Identity', 'Typography'],
    posted: '2h',
    match: 97,
    why: 'Identity systems + type-led work maps directly to your portfolio direction.',
  },
  {
    id: 2,
    title: 'Visual Designer',
    company: 'Someplace Studio',
    location: 'Amsterdam',
    workType: 'Remote',
    type: 'Full-time',
    salary: '€60–75k',
    salaryNum: 67,
    email: 'hello@someplace.studio',
    tags: ['Brand', 'Motion'],
    posted: '5h',
    match: 94,
    why: 'Studio does brand + web end-to-end — matches your full-stack design range.',
  },
  {
    id: 3,
    title: 'Brand Identity Designer',
    company: 'KOTO Studio',
    location: 'London',
    workType: 'Remote',
    type: 'Contract',
    salary: '$70–90k',
    salaryNum: 80,
    email: 'apply@koto.studio',
    tags: ['Identity', 'Systems'],
    posted: '1d',
    match: 91,
    why: 'Systems-driven identity work; your structured token approach is a direct fit.',
  },
  {
    id: 4,
    title: 'Design Lead',
    company: 'Monograph',
    location: 'San Francisco',
    workType: 'Hybrid',
    type: 'Full-time',
    salary: '$90–120k',
    salaryNum: 105,
    email: 'design@monograph.io',
    tags: ['Leadership', 'Product'],
    posted: '1d',
    match: 88,
    why: 'Product + brand hybrid; your app-building work covers the product half.',
  },
  {
    id: 5,
    title: 'Graphic Designer',
    company: 'Hawkins Brown',
    location: 'London',
    workType: 'On-site',
    type: 'Full-time',
    salary: '£45–55k',
    salaryNum: 50,
    email: 'studio@hawkinsbrown.com',
    tags: ['Brand', 'Print'],
    posted: '2d',
    match: 85,
    why: 'Architecture studio needing editorial brand work — your cinematic register fits.',
  },
  {
    id: 6,
    title: 'Creative Director',
    company: 'Athletics',
    location: 'New York',
    workType: 'Remote',
    type: 'Full-time',
    salary: '$110–140k',
    salaryNum: 125,
    email: 'join@athletics.com',
    tags: ['Direction', 'Strategy'],
    posted: '2d',
    match: 82,
    why: 'Stretch role — strategy emphasis exceeds current years, but portfolio depth compensates.',
  },
  {
    id: 7,
    title: 'Brand Designer',
    company: 'Superside',
    location: 'Global',
    workType: 'Remote',
    type: 'Full-time',
    salary: '$65–85k',
    salaryNum: 75,
    email: 'talent@superside.com',
    tags: ['Brand', 'Scale'],
    posted: '3d',
    match: 80,
    why: 'High-volume brand production; steady remote income.',
  },
  {
    id: 8,
    title: 'Visual Identity Designer',
    company: 'DesignStudio',
    location: 'New York',
    workType: 'Hybrid',
    type: 'Full-time',
    salary: '$75–95k',
    salaryNum: 85,
    email: 'work@design.studio',
    tags: ['Identity', 'Research'],
    posted: '3d',
    match: 78,
    why: 'Research-heavy process; your audit-tool thinking translates well.',
  },
]

export const STAGES = [
  { id: 'sent',      label: 'Sent',      color: '#52504c' },
  { id: 'opened',    label: 'Opened',    color: '#f2994a' },
  { id: 'replied',   label: 'Replied',   color: '#b8f5a0' },
  { id: 'interview', label: 'Interview', color: '#6fcf97' },
]
